AWSTemplateFormatVersion: 2010-09-09
Description: "CloudFormation template to create a custom VPC, EC2 instance (for app),\
  \ and RDS MySQL database for CI/CD pipeline project.\n"
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access
  DBUser:
    Type: String
    Description: Database username
    MinLength: 1
  DBPassword:
    Type: String
    Description: Database password
    NoEcho: true
    MinLength: 8
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: CICD-VPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: MyVPC
      InternetGatewayId:
        Ref: InternetGateway
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ''
      Tags:
      - Key: Name
        Value: Public-Subnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs: ''
      Tags:
      - Key: Name
        Value: Private-Subnet
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MyVPC
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: PublicRouteTable
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP, HTTPS, SSH
      VpcId:
        Ref: MyVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access from web server
      VpcId:
        Ref: MyVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId:
          Ref: WebSecurityGroup
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      KeyName:
        Ref: KeyName
      SubnetId:
        Ref: PublicSubnet
      SecurityGroupIds:
      - Ref: WebSecurityGroup
      Tags:
      - Key: Name
        Value: CICD-WebServer
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash\napt update -y\napt install -y apache2\nsystemctl\
            \ enable apache2\nsystemctl start apache2\necho \"<h1>Welcome to the AWS\
            \ CI/CD CloudFormation Project</h1>\" > /var/www/html/index.html\n"
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: cicd-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername:
        Ref: DBUser
      MasterUserPassword:
        Ref: DBPassword
      VPCSecurityGroups:
      - Ref: DBSecurityGroup
      DBSubnetGroupName:
        Ref: MyDBSubnetGroup
      PubliclyAccessible: false
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
      - Ref: PrivateSubnet
Outputs:
  VPCId:
    Value:
      Ref: MyVPC
  WebServerPublicIP:
    Value:
      Fn::GetAtt:
      - WebServer
      - PublicIp
  RDSEndpoint:
    Value:
      Fn::GetAtt:
      - MyDBInstance
      - Endpoint.Address
